name: Build and push base CI Docker image

on:
  workflow_dispatch:
    inputs:
      terraform:
        description: 'Terraform version'
        required: false
        default: '1.5.7'
  push:
    paths:
      - 'ci-docker-image/**'
  pull_request:
    paths:
      - 'ci-docker-image/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  TERRAFORM_VERSION: ${{ github.event.inputs.terraform || '1.5.7' }}

jobs:
  build_docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            name=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            name=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-terraform-v${{ env.TERRAFORM_VERSION }}
          tags: |
            type=sha,format=long
            type=ref,event=branch
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
            type=raw,value=terraform-v${{ env.TERRAFORM_VERSION }}
            

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          build-args: |
            TERRAFORM_VERSION=${{ env.TERRAFORM_VERSION }}
          context: .
          file: ./ci-docker-image/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}